title: 'Jared Sackett'
default_lang: en
author:
  name: 'Jared Sackett'
  email: jake850@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Jared Sackett''s portfolio and blog website'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
