# Site Settings
title: "Jared Sackett"
description: "This is not a clever tagline"



# Build Settings


markdown: kramdown
permalink: pretty

port: 8000

include: ['_includes/work']

sass:
    sass_dir: assets/css
    style: :nested

plugins:
    - jekyll-pug


destination: ~/jasackettcomSite/built
